
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import Sidebar from "@/components/layout/Sidebar";

export default function RootLayout({ children }) {
  return (
    <div className="pt-32">
      <div className="container px-5 xl:px-20 mx-auto">
        <div className="flex gap-14">
          <Sidebar />
          <main className="w-full" >
            {children}
          </main>
        </div>
      </div>
    </div>

  );
}
