import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

export const metadata = {
  title: "پلتفرم آموزشی تکا | Techa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body>
        <Header />
        <main className="mb-40 md:mb-60">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
