import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { AuthProvider } from "../components/contexts/AuthContext";
export const metadata = {
  title: "پلتفرم آموزشی تکا | Techa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body>
        <AuthProvider>
          <Header />
          <main className="mb-40 md:mb-60">{children}</main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
