import { Code2, Database } from "lucide-react";

export const marketData = [
    {
        slug: "react",
        title: "React Front-End",
        icon: Code2,
        description:
            "تحلیل بازار کار برنامه‌نویس React بر اساس آگهی‌های استخدام منتشرشده در جابینجا، جاب ویژن و ای استخدام.",
        updatedAt: "تیر ۱۴۰۵",
        ads: { total: 1200, active: 315 },
        demand: { text: "بسیار بالا", value: 95 },
        salaries: {
            junior: "20 - 35 میلیون",
            mid: "35 - 60 میلیون",
            senior: "60 - 90+ میلیون",
            remote: "40 - 120+ میلیون",
        },
        companies: [
            { name: "دیجی‌کالا", jobs: 180, salary: "35 - 70 میلیون" },
            { name: "اسنپ", jobs: 145, salary: "30 - 65 میلیون" },
            { name: "تپسی", jobs: 72, salary: "30 - 60 میلیون" },
            { name: "علی‌بابا", jobs: 64, salary: "35 - 70 میلیون" },
            { name: "فیلیمو", jobs: 55, salary: "35 - 75 میلیون" },
            { name: "فناپ", jobs: 91, salary: "30 - 70 میلیون" },
        ],
        skills: [
            { name: "HTML", percent: 98, covered: true },
            { name: "CSS", percent: 97, covered: true },
            { name: "JavaScript (ES6+)", percent: 95, covered: true },
            { name: "React", percent: 94, covered: true },
            { name: "Git & GitHub", percent: 90, covered: true },
            { name: "REST API", percent: 87, covered: true },
            { name: "Responsive Design", percent: 86, covered: true },
            { name: "Redux Toolkit", percent: 78, covered: true },
            { name: "Axios", percent: 74, covered: true },
            { name: "TypeScript", percent: 69, covered: true },
            { name: "Tailwind CSS", percent: 67, covered: true },
            { name: "Next.js", percent: 51, covered: true },
            { name: "Docker", percent: 32, covered: false },
            { name: "GraphQL", percent: 18, covered: false },
        ],
        roadmap: [
            "HTML",
            "CSS",
            "JavaScript",
            "Git",
            "React",
            "REST API",
            "Redux Toolkit",
            "TypeScript",
            "Next.js",
            "ساخت پروژه واقعی",
            "رزومه و GitHub",
            "ورود به بازار کار",
        ],
    },
    {
        slug: "sql",
        title: "SQL Server",
        icon: Database,
        description:
            "تحلیل بازار کار SQL Server Developer و Database Developer بر اساس آگهی‌های استخدام.",
        updatedAt: "تیر ۱۴۰۵",
        ads: { total: 720, active: 185 },
        demand: { text: "زیاد", value: 87 },
        salaries: {
            junior: "18 - 30 میلیون",
            mid: "30 - 50 میلیون",
            senior: "50 - 80+ میلیون",
            remote: "35 - 100+ میلیون",
        },
        companies: [
            { name: "فناپ", jobs: 74, salary: "30 - 65 میلیون" },
            { name: "راهکاران", jobs: 42, salary: "28 - 55 میلیون" },
            { name: "همراه اول", jobs: 35, salary: "30 - 60 میلیون" },
            { name: "بانک ملت", jobs: 26, salary: "30 - 55 میلیون" },
            { name: "آسان پرداخت", jobs: 41, salary: "30 - 60 میلیون" },
        ],
        skills: [
            { name: "SELECT", percent: 99, covered: true },
            { name: "JOIN", percent: 98, covered: true },
            { name: "GROUP BY", percent: 95, covered: true },
            { name: "Stored Procedure", percent: 94, covered: true },
            { name: "View", percent: 92, covered: true },
            { name: "Function", percent: 88, covered: true },
            { name: "Index", percent: 86, covered: true },
            { name: "Query Optimization", percent: 81, covered: true },
            { name: "Transaction", percent: 73, covered: true },
            { name: "Trigger", percent: 68, covered: true },
            { name: "Execution Plan", percent: 55, covered: true },
            { name: "Replication", percent: 28, covered: false },
        ],
        roadmap: [
            "SELECT",
            "WHERE",
            "JOIN",
            "GROUP BY",
            "Sub Query",
            "View",
            "Stored Procedure",
            "Function",
            "Index",
            "Optimization",
            "Performance Tuning",
            "ورود به بازار کار",
        ],
    },
];