// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import Sidebar from "../../../components/docs/Sidebar";

export default function RootLayout({ children }) {
  return (
    <div className="min-h-screen to-white pt-32">
      <div className="container mx-auto px-5 lg:px-0 xl:px-5 2xl:px-20">
        <div className='grid grid-cols-12 gap-10'>
          <Sidebar />
          <div className='col-span-8'>
            {children}
          </div>
        </div>
      </div>
    </div>
  );
}
