// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
"use client"
import { usePathname } from "next/navigation";
import Sidebar from "../../../components/courses/Sidebar";

export default function RootLayout({ children }) {

  const pathname = usePathname()

  if (pathname?.includes('/exercises')) {
    return <div className="min-h-screen to-white pt-32">{children}</div>
  }

  return (
    <div className="min-h-screen to-white pt-32">
      <div className="container mx-auto px-5 lg:px-0 xl:px-5 2xl:px-20">
        <div className='flex flex-col-reverse lg:grid lg:grid-cols-12 xl:gap-10 gap-5'>
          <Sidebar />
          <div className='col-span-8'>
            {children}
          </div>
        </div>
      </div>
    </div>
  );
}
