name: Deploy Techa

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"

          Set-Location C:\inetpub\techa

          git config --global --add safe.directory C:/inetpub/techa

          git pull origin main

          npm install

          npm run build

          & "C:\Users\Administrator\AppData\Roaming\npm\pm2.cmd" restart techa
